spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: 'true'
    hibernate:
      ddl-auto: update

jwt-time-expiration-in-minutes: 5

