spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    url: jdbc:mariadb://localhost:3306/challenge
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: password
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: 'true'
    hibernate:
      ddl-auto: update

jwt-time-expiration-in-minutes: 5

campo:
  email:
    obrigatorio: O campo email é obrigatorio
    invalido: O campo email é invalido
  icms:
    negativo: O campo icms tem que ser no minimo maior que zero
    obrigatorio: O campo icms é obrigatorio
  tipousuario:
    obrigatorio: O campo tipo de usuario é obrigatorio
  usuario:
    obrigatorio: O campo usuario é obrigatorio
  custo:
    obrigatorio: O campo custo é obrigatorio
    negativo: O campo custo tem que ser no minimo maior que zero
  senha:
    obrigatorio: O campo senha é obrigatorio
  sku:
    obrigatorio: O campo sku é obrigatorio
  venda:
    obrigatorio: O campo valor de venda principal é obrigatorio
  quantidade:
    obrigatorio: O campo quantidade é obrigatorio
    negativo: O campo valor de revenda tem que ser no minimo zero
  imagem:
    obrigatorio: O campo imagem é obrigatorio
  revenda:
    negativo: O campo valor de revenda tem que ser no minimo maior que zero
  categoria:
    obrigatorio: O campo categoria é obrigatorio
  nome:
    obrigatorio: O campo nome é obrigatorio
    size: O campo nome precisa de no minimo 8 e no maximo 50 carateres
