spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: gabriel
    url: jdbc:postgresql://localhost:5432/test
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: admin
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop

jwt-time-expiration-in-minutes: 1

