spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    url: jdbc:mariadb://localhost:3306/challenge
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: password
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: 'true'
    hibernate:
      ddl-auto: update